export const intros: Record<string, string | null> = {
  uccle:
    "Uccle (1180) est l'une des plus vastes communes de la Région de Bruxelles-Capitale, marquée par ses maisons de maître, ses villas années 1930 et ses immeubles d'appartements en bordure du bois de la Cambre. Macar y intervient régulièrement pour des rénovations intérieures et extérieures complètes : isolation de façade et crépi, peinture, parquet, plafonds en gyproc. Côté toiture, le tissu uccloise mélange charpentes anciennes en tuiles, toits plats en Derbigum ou EPDM, et nombreuses lucarnes et verrières typiques. Nos équipes prennent en charge la pose d'échafaudages, le remplacement des corniches et gouttières en zinc naturel, ainsi que la mise en conformité électrique du tableau (RGIE) sur les biens plus anciens. Pour la plomberie, nous installons et remplaçons chaudières à condensation, sanitaires et canalisations, avec détection de fuites par caméra. Devis gratuit sur mesure pour chaque chantier à Uccle.",
  schaerbeek:
    "Schaerbeek (1030) compte parmi les communes les plus densément bâties de Bruxelles, avec son patrimoine de maisons de rapport, ses immeubles néoclassiques et ses nombreuses copropriétés. Macar y mène des chantiers de rénovation intérieure (peinture, plafonds, carrelage, parquet) et extérieure (isolation de façade, crépi, rejointoiement de briques). Sur la toiture, les charpentes traditionnelles en tuiles, les corniches en zinc et les noues en plomb demandent un savoir-faire spécifique que nos couvreurs maîtrisent. Pour les installations électriques, nous remplaçons les tableaux anciens et mettons en conformité RGIE l'ensemble du circuit, indispensable lors d'une vente ou d'une mise en location. Côté plomberie, nos équipes interviennent sur les chaudières, le chauffage central, les sanitaires et les canalisations en grès souvent remplacées par du PVC. Devis gratuit pour chaque intervention à Schaerbeek.",
  ixelles:
    "Ixelles (1050) abrite une grande diversité bâtie : maisons Art nouveau, immeubles modernistes, copropriétés autour des étangs et du quartier Châtelain. Macar accompagne propriétaires et copropriétés sur l'ensemble de leurs travaux de rénovation à Ixelles. En intérieur, nos équipes prennent en charge la peinture, les plafonds gyproc, le carrelage de salles de bain et le parquet flottant. En extérieur, isolation de façade, crépi, peinture façade et rejointoiement des briques. Pour la toiture, nous intervenons sur les toits plats Derbigum et EPDM fréquents sur les immeubles ixellois, ainsi que sur les corniches en zinc et la pose de velux. Côté installations électriques, mise en conformité RGIE complète du tableau et du câblage, indispensable pour la vente ou la location. La plomberie couvre chaudières, sanitaires, détection de fuites et remplacement des canalisations. Devis gratuit sur mesure pour chaque chantier à Ixelles.",
  "woluwe-saint-pierre":
    "Woluwe-Saint-Pierre (1150) est une commune résidentielle de l'est bruxellois, où Macar intervient très fréquemment. Le bâti combine villas années 1920-1960, immeubles à appartements en bordure d'avenues larges et maisons unifamiliales aux jardins arrière généreux. Nos chantiers de toiture y portent souvent sur des charpentes en tuiles à reprendre, des toits plats Derbigum ou EPDM à refaire sur les annexes et garages, des velux à remplacer et des corniches en zinc à redresser ou neuves. En rénovation, nous menons des dossiers complets : isolation par l'extérieur de façades arrière, peinture, plafonds gyproc, plâtrerie et carrelage de salle de bain. Côté plomberie, nos équipes installent et remplacent chaudières à condensation, sanitaires et radiateurs ; côté électricité, mise en conformité RGIE complète du tableau et du câblage avant vente ou location. Devis gratuit pour tout chantier à Woluwe-Saint-Pierre.",
  evere:
    "Evere (1140) est une commune en mutation, marquée par une mixité forte entre maisons mitoyennes d'après-guerre, immeubles à appartements et zones plus contemporaines. Macar y mène régulièrement des chantiers de toiture, plomberie et rénovation. Sur la toiture, nos couvreurs interviennent sur les toitures en pente comme sur les toits plats, ainsi que sur les corniches, descentes d'eau en zinc et solins de cheminée. Pour la rénovation, nous prenons en charge l'isolation de façade (insufflation de mur creux ou ITE selon le bâti), la peinture, les plafonds gyproc, le carrelage et la plâtrerie. Côté installations électriques, la mise en conformité RGIE concerne particulièrement les biens des années 1950-1970 nombreux à Evere, avec remplacement de tableau et reprise du câblage. En plomberie, nos équipes traitent chaudières, sanitaires, détection de fuites et remplacement de canalisations. Devis gratuit sur chaque chantier à Evere.",
  // TODO P2.2 copy: write ~200 mots FR
  etterbeek: null,
  "saint-gilles": null,
  forest: null,
  "woluwe-saint-lambert": null,
  anderlecht: null,
  jette: null,
  "molenbeek-saint-jean": null,
};
