import localFont from "next/font/local";
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { Providers } from "./providers";
import { NavBar } from "./_components/navbar";
import { Footer } from "./_components/footer";

const open_sans = Open_Sans({ subsets: ['latin'] })
const raptor = localFont({
  src: [
    {
      path: "../../public/fonts/raptor/Semibold.otf",
      weight: "600"
    }
  ],
  variable: "--font-raptor"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} text-text bg-background antialiased`}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers></body>
    </html >
  )
}
