/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M2iW6s1DjUZ
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"
import { SecondHeading } from "@/app/_components/textStyles"

export function contact_form() {
  return (
    <Card className="mx-auto max-w-md p-6 bg-white rounded-xl shadow-md space-y-6">
      <CardContent>
        <div className="space-y-8">
          <div className="space-y-2">
            <SecondHeading customClasses="text-xl lg:text-3xl 2xl:text-4xl">Contactez-nous</SecondHeading>
            <p className="text-gray-500">Nous sommes à l'écoute de vos besoins pour toute rénovation, plomberie, électricité ou toiture</p>
          </div>
          <div className="space-y-3">
            <div className="space-y-2">
              <Label htmlFor="name">Nom et Prénom</Label>
              <Input id="name" placeholder="Entrez votre nom et prénom" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Entrez votre email" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="telephone">Téléphone</Label>
              <Input id="telephone" placeholder="04XXXXXXXX" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message">Message</Label>
              <Textarea className="min-h-[100px]" id="message" placeholder="Bonjour, je serai intéressé par des services de ..." />
            </div>
            <Button className="w-full" variant="accent1">Envoyer</Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
