/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M2iW6s1DjUZ
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function contact_form() {
  return (
    <Card className="p-6 bg-white rounded-xl shadow-md space-y-6">
      <CardContent>
        <div className="space-y-8">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold">Contact Us</h2>
            <p className="text-gray-500">Fill out the form below and we'll get back to you as soon as possible.</p>
          </div>
          <div className="space-y-3">
            <div className="space-y-2">
              <Label htmlFor="name">Nom et Prénom</Label>
              <Input id="name" placeholder="Entrez votre nom et prénom" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Entrez votre email" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="telephone">Téléphone</Label>
              <Input id="telephone" placeholder="Entrez votre numéro de téléphone" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message">Message</Label>
              <Textarea className="min-h-[100px]" id="message" placeholder="Entrez votre message" />
            </div>
            <Button>Submit</Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
