/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M2iW6s1DjUZ
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"
import { P, SecondHeading } from "@/app/_components/textStyles"
import React, { useState } from "react";
import { z } from "zod";
import axios from "axios";
import { SecondaryButton } from "@/app/_components/buttons"

const contactFormSchema = z.object({
  name: z.string().optional(),
  email: z.string().email("Adresse email doit contenir un @; ").nonempty("Email est requis"),
  telephone: z.string().nonempty("Numéro de téléphone requis"),
  message: z.string().nonempty("Un message expliquant la demande est requis"),
});

type ValidationErrorsType = {
  name?: string;
  email?: string;
  telephone?: string;
  message?: string;
};

export function contact_form() {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    telephone: "",
    message: "",
  });
  const [validationErrors, setValidationErrors] = useState<ValidationErrorsType>({});
  const [submissionSuccess, setSubmissionSuccess] = useState(false);
  const [backendError, setBackendError] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prevData => ({ ...prevData, [name]: value }));
  };

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    setValidationErrors({});

    try {
      contactFormSchema.parse(formData);
      const formEndpoint = process.env.NEXT_PUBLIC_FORMSPREE_ENDPOINT?.trim();
      if (!formEndpoint) {
        setBackendError(true);
        return;
      }
      axios
        .post(
          formEndpoint,
          formData,
          {
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json'
            }
          }
        )
        .then(function (response) {
          setFormData({
            name: "",
            email: "",
            telephone: "",
            message: "",
          });
          setSubmissionSuccess(true);
        })
        .catch(function (error) {
          setBackendError(true)
        });
    } catch (error) {
      if (error instanceof z.ZodError) {
        //console.error("Validation errors", error.flatten());
        setValidationErrors(error.flatten().fieldErrors);
      } else {
        setBackendError(true)
      }
    }
  };


  return (
    <Card className="mx-auto px-1 sm:px-4 py-10 bg-white rounded-xl shadow-md space-y-6">
      <CardContent>
        {submissionSuccess ? (
          <div className="" role="status" aria-live="polite" aria-atomic="true">
            <SecondHeading customClasses="text-xl lg:text-2xl 2xl:text-[30px] mt-2 mb-4">Merci pour votre confiance !</SecondHeading>
            <P content="Merci pour votre demande! Nous allons la traiter dans les plus brefs délais." />
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-6" noValidate>
            {Object.keys(validationErrors).length > 0 && (
              <p className="text-sm text-red-600" role="alert" aria-live="polite" aria-atomic="true">
                Le formulaire contient des erreurs. Veuillez corriger les champs indiqués.
              </p>
            )}
            <div className="space-y-8">
              <div className="space-y-2">
                <SecondHeading customClasses="text-xl lg:text-2xl 2xl:text-[30px] mt-2 mb-4">Contactez-nous</SecondHeading>
                <p className="text-gray-500">Nous sommes à l'écoute de vos besoins pour toute rénovation, plomberie, électricité ou toiture.</p>
              </div>
              <div className="space-y-3">
                <div className="space-y-2">
                  <Label htmlFor="name">Nom et Prénom</Label>
                  <Input id="name" name="name" placeholder="Entrez votre nom et prénom" value={formData.name} onChange={handleChange} />
                  {validationErrors.name && <p className="flex h-10 text-sm text-red-500">{validationErrors.name}</p>}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" name="email" placeholder="Entrez votre email" value={formData.email} onChange={handleChange} />
                  {validationErrors.email && <p className="flex h-10 text-sm text-red-500">{validationErrors.email}</p>}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="telephone">Téléphone</Label>
                  <Input id="telephone" name="telephone" placeholder="04XXXXXXXX" value={formData.telephone} onChange={handleChange} />
                  {validationErrors.telephone && <p className="flex h-10 text-sm text-red-500">{validationErrors.telephone}</p>}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea className="min-h-[100px]" id="message" name="message" placeholder="Bonjour, je serais intéressé par des services de ..." value={formData.message} onChange={handleChange} />
                  {validationErrors.message && <p className="flex h-10 text-sm text-red-500">{validationErrors.message}</p>}
                </div>
                <Button type="submit" className="group rounded-lg relative px-5 py-3 lg:px-6 lg:py-3 text-xs lg:text-sm bg-white text-accent1 border border-accent1 font-regular hover:bg-accent1 hover:text-background w-full" variant="accent1">Envoyer</Button>
                <p className="text-sm text-gray-500 italic">Nous ne partageons vos informations à <span className="underline underline-offset-4">aucun</span> tiers.</p>
                {backendError && (
                  <div className="flex h-10 text-sm text-red-700" role="alert" aria-live="assertive" aria-atomic="true">
                    Oups quelque chose s'est mal passé, contactez-nous par email à <a href="mailto:info@macar.be" className="underline underline-offset-4">info@macar.be</a>
                  </div>
                )}
              </div>
            </div>
          </form>
        )}
      </CardContent>
    </Card >
  )
}
