/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NBYYs817uBa
 */
import { Button } from "@/components/ui/button"

export function Jobs() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <nav className="flex justify-between items-center py-6">
        <div className="flex items-center">
          <img
            alt="Company logo"
            className="h-10"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "120/40",
              objectFit: "cover",
            }}
            width="120"
          />
          <div className="hidden md:flex space-x-8 ml-10">
            <a className="text-gray-500 hover:text-gray-900" href="#">
              Accueil
            </a>
            <a className="text-gray-500 hover:text-gray-900" href="#">
              À propos de nous
            </a>
            <a className="text-gray-500 hover:text-gray-900" href="#">
              Services
            </a>
          </div>
        </div>
        <Button className="hidden md:block" variant="outline">
          Contactez-nous
        </Button>
      </nav>
      <header className="mt-12">
        <h1 className="text-6xl font-bold text-gray-900 leading-tight">Nous recrutons!</h1>
        <p className="mt-4 text-xl text-gray-600">
          Rejoignez notre équipe et aidez-nous à créer des espaces incroyables.
        </p>
      </header>
      <div className="mt-12 grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="md:col-span-2">
          <img
            alt="We are hiring image"
            className="w-full h-auto"
            height="400"
            src="/placeholder.svg"
            style={{
              aspectRatio: "1113/400",
              objectFit: "cover",
            }}
            width="1113"
          />
        </div>
        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-gray-900">Carrières chez Nous</h2>
          <p className="text-gray-600">
            Si vous êtes passionné par la rénovation, la construction ou le design, nous aimerions vous rencontrer. Nous
            recherchons des personnes talentueuses pour rejoindre notre équipe dynamique.
          </p>
          <Button>Postuler maintenant</Button>
        </section>
        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-gray-900">Pourquoi travailler avec nous?</h2>
          <p className="text-gray-600">
            Nous offrons un environnement de travail stimulant, des projets variés et la possibilité de croître
            professionnellement. Découvrez une culture d'entreprise qui valorise l'innovation et le travail d'équipe.
          </p>
        </section>
        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-gray-900">Ouvrier polyvalent (indépendant) H/F/X</h2>
          <h3 className="text-2xl font-bold text-gray-700">Responsabilités :</h3>
          <p className="text-gray-600">
            - Assurer la réalisation des travaux de rénovation complète, de plomberie, d'installations électriques ou de
            toiture conformément aux standards de qualité de l'entreprise.
            <br />- Gérer efficacement les ressources et les matériaux sur le lieu de travail.
            <br />- Respecter les règles de sécurité sur le lieu de travail.
            <br />- Fournir un excellent service client, en tenant compte des besoins et des attentes des clients.
            <br />- Collaborer avec l'équipe pour garantir la réalisation efficace des projets.
          </p>
          <h3 className="text-2xl font-bold text-gray-700">Critères de sélection :</h3>
          <p className="text-gray-600">
            - Expérience professionnelle : Minimum 2 ans d'expérience dans le secteur du bâtiment, en particulier dans
            les travaux de rénovation, la plomberie, l'électricité et la toiture.
          </p>
        </section>
      </div>
    </div>
  )
}
