/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A8NsaV18lkV
 */

import { MainHeading, P, SecondHeading, ThirdHeading } from "@/app/_components/textStyles"
import Image from 'next/image'
import logo_homeras from "/src/app/about/companies/homeras.png";
import logo_ethias from "/src/app/about/companies/ethias.png";

export function Trusted() {
  return (
    <section className="w-full">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-8">
        <ThirdHeading> Ils nous ont fait confiance </ThirdHeading>
        <div className="grid w-full grid-cols-2 lg:grid-cols-5 items-center justify-center gap-8 lg:gap-12">
          <div className="col-span-2 lg:col-span-5 flex justify-center">
            <Image
              alt="Homeras"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              height="80"
              width="160"
              src={logo_homeras}
            />
            <Image
              alt="Ethias"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              height="80"
              width="160"
              src={logo_ethias}
            />
          </div>
        </div>
      </div>
    </section>
  )
}
