/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A8NsaV18lkV
 */

import { MainHeading, P, SecondHeading, ThirdHeading } from "@/app/_components/textStyles"
import Image from 'next/image'
import logo_homeras from "/src/app/about/companies/homeras.png";
import logo_ethias from "/src/app/about/companies/ethias.png";
import logo_ag from "/src/app/about/companies/ag.png";

export function Trusted({ titleAlignment, imageAlignment, headingSize, imageSize, imageClass }) {
  return (
    <section className="w-full">
      <div className={`${titleAlignment}>`}> {/*Basically "justify-center" for Title alignement*/}
        <ThirdHeading customClasses={headingSize}> Ils nous ont fait confiance </ThirdHeading>
        <div className={`grid w-full grid-cols-2 lg:grid-cols-5 ${imageAlignment} gap-8 lg:gap-12"`}> {/* Basically "items-center justify-center" for Image alignement */}
          <div className={`col-span-2 lg:col-span-5 flex ${imageAlignment} ${imageClass}`}>
            <Image
              alt="Homeras"
              className={`aspect-[2/1] overflow-hidden rounded-lg object-contain ${imageAlignment} ${imageClass}`}
              height={imageSize.height}
              width={imageSize.width}
              src={logo_homeras}
            />
            <Image
              alt="Ethias"
              className={`aspect-[2/1] overflow-hidden rounded-lg object-contain ${imageAlignment} ${imageClass}`}
              height={imageSize.height}
              width={imageSize.width}
              src={logo_ethias}
            />
            <Image
              alt="AG Assurance"
              className={`aspect-[2/1] overflow-hidden rounded-lg object-contain ${imageAlignment} ${imageClass}`}
              height={imageSize.height}
              width={imageSize.width}
              src={logo_ag}
            />
          </div>
        </div>
      </div>
    </section>
  )
}
